export default {
    GET_USER_INFO: 'GET_USER_INFO',
    GET_ALL_DEVICE: 'GET_ALL_DEVICE',
    GET_ALL_ROLES: 'GET_ALL_ROLES',
    GET_ALL_TESTING: 'GET_ALL_TESTING',
    CHANGE_STATUS_TO_WORK: 'CHANGE_STATUS_TO_WORK'
};